import type { Location } from './types';

export const locations: Location[] = [
  {
    id: 'loc_1',
    name: 'Downtown Plaza',
    currentDensity: 68,
    maxCapacity: 200,
    historicalData: [
      { time: '9am', density: 25 },
      { time: '10am', density: 40 },
      { time: '11am', density: 60 },
      { time: '12pm', density: 85 },
      { time: '1pm', density: 90 },
      { time: '2pm', density: 75 },
      { time: '3pm', density: 70 },
      { time: '4pm', density: 65 },
      { time: '5pm', density: 68 },
    ],
  },
  {
    id: 'loc_2',
    name: 'City Park',
    currentDensity: 35,
    maxCapacity: 150,
    historicalData: [
      { time: '9am', density: 10 },
      { time: '10am', density: 15 },
      { time: '11am', density: 25 },
      { time: '12pm', density: 40 },
      { time: '1pm', density: 45 },
      { time: '2pm', density: 42 },
      { time: '3pm', density: 38 },
      { time: '4pm', density: 30 },
      { time: '5pm', density: 35 },
    ],
  },
  {
    id: 'loc_3',
    name: 'Central Station',
    currentDensity: 180,
    maxCapacity: 250,
    historicalData: [
      { time: '9am', density: 120 },
      { time: '10am', density: 150 },
      { time: '11am', density: 160 },
      { time: '12pm', density: 175 },
      { time: '1pm', density: 170 },
      { time: '2pm', density: 165 },
      { time: '3pm', density: 180 },
      { time: '4pm', density: 190 },
      { time: '5pm', density: 180 },
    ],
  },
  {
    id: 'loc_4',
    name: 'Riverside Mall',
    currentDensity: 150,
    maxCapacity: 300,
    historicalData: [
      { time: '9am', density: 50 },
      { time: '10am', density: 80 },
      { time: '11am', density: 120 },
      { time: '12pm', density: 160 },
      { time: '1pm', density: 170 },
      { time: '2pm', density: 165 },
      { time: '3pm', density: 155 },
      { time: '4pm', density: 140 },
      { time: '5pm', density: 150 },
    ],
  },
];
